import pandas as pd
import yfinance as yf
import mysql.connector
from mysql.connector import Error

# Read the CSV file generated by spider into a DataFrame
df = pd.read_csv('/home/alvcantu/stocks/etl/raw_company_list_url.csv')

# Extract required info from yfinance
def get_stock_info(ticker):
    # Manually adjust ticker symbols as needed
    # Saudi Aramco
    if ticker == '2222':
        ticker = '2222.SR'
    # Berkshire Hathaway
    if ticker == 'BRK.A':
        ticker = 'BRK-A'
    # TSMC
    if ticker == '2330':
        ticker = 'TSMC34.SA'
    # PetroChina
    elif ticker == '857':
        ticker = '0857.HK'

    # Extract stock information
    stock = yf.Ticker(ticker)
    info = stock.info

    # Extract relevant information from the stock info
    return [
        ticker,
        info.get('shortName'),
        info.get('country'),
        info.get('website'),
        info.get('industry'),
        info.get('financialCurrency'),
        info.get('longBusinessSummary')
    ]

# Create DataFrame with stock information
columns = ['ticker', 'name', 'country', 'website', 'industry', 'currency', 'summary']
ticker_df = pd.DataFrame([get_stock_info(ticker) for ticker in df['ticker']], columns=columns)

ticker_df = ticker_df.dropna()


# Data quality checks
def data_quality_checks(df):
    if df.isnull().values.any():
        raise ValueError("Data contains empty values")

    expected_types = {col: str for col in columns}
    for column, expected_type in expected_types.items():
        if not df[column].map(type).eq(expected_type).all():
            raise TypeError(f"Data type mismatch in column {column}")

    if not df['currency'].str.len().eq(3).all():
        raise ValueError("Currency column contains values not of length 3")

# Perform data quality checks above
data_quality_checks(ticker_df)

# Database connection and insertion
try:
    mydb = mysql.connector.connect(
        host="alvcantu.mysql.pythonanywhere-services.com",
        user="alvcantu",
        password="h63Efp09-d",
        database="alvcantu$default"
    )

    if mydb.is_connected():
        cursor = mydb.cursor()

        # Prepare the INSERT statement into MySQL ST_DimCompany table
        insert_query = """
            INSERT INTO ST_DimCompany (ticker, name, country, website, industry, currency, summary)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            ON DUPLICATE KEY UPDATE
            name=VALUES(name), country=VALUES(country), website=VALUES(website),
            industry=VALUES(industry), currency=VALUES(currency), summary=VALUES(summary)
        """

        # Insert or update rows by executing query above
        cursor.executemany(insert_query, ticker_df.values.tolist())
        mydb.commit()

        print(f"{cursor.rowcount} record(s) upserted.")

# Error clause
except Error as e:
    print(f"Error: {e}")

# Close database
finally:
    if 'mydb' in locals() and mydb.is_connected():
        cursor.close()
        mydb.close()
        print("MySQL connection is closed")