import pandas as pd
import yfinance as yf
import mysql.connector
from mysql.connector import Error
import time
from requests.exceptions import HTTPError

# Read the CSV file generated by spider into a DataFrame
df = pd.read_csv('/home/alvcantu/stocks/etl/raw_company_list_url.csv')

# Function to fetch stock information from Yahoo Finance
def get_stock_info(ticker, retries=5, initial_delay=2):
    # Manually adjust ticker symbols as needed
    if ticker == '2222':
        ticker = '2222.SR'  # Saudi Aramco
    elif ticker == 'BRK.A':
        ticker = 'BRK-A'    # Berkshire Hathaway
    elif ticker == '2330':
        ticker = 'TSMC34.SA'  # TSMC
    elif ticker == '857':
        ticker = '0857.HK'   # PetroChina

    # Attempt to fetch stock information with retries
    for attempt in range(retries):
        try:
            stock = yf.Ticker(ticker)  # Use custom session
            info = stock.info
            return [
                ticker,
                info.get('shortName'),
                info.get('country'),
                info.get('website'),
                info.get('industry'),
                info.get('financialCurrency'),
                info.get('longBusinessSummary')
            ]
        except HTTPError as e:
            if e.response.status_code == 429:
                delay = initial_delay * (2 ** attempt)
                print(f"429 Error for {ticker}: Retrying in {delay} seconds (Attempt {attempt + 1}/{retries})...")
                time.sleep(delay)
            else:
                print(f"HTTP Error {e.response.status_code} for {ticker}: {e}")
                return [ticker] + [None] * 6
        except Exception as e:
            print(f"Error fetching {ticker}: {e}")
            return [ticker] + [None] * 6
        time.sleep(1)

    print(f"Failed to fetch data for {ticker} after {retries} attempts.")
    return [ticker] + [None] * 6

# Define columns for the DataFrame
columns = ['ticker', 'name', 'country', 'website', 'industry', 'currency', 'summary']

# Fetch stock information for each ticker
ticker_data = []
for ticker in df['ticker']:
    result = get_stock_info(ticker)
    ticker_data.append(result)
    time.sleep(2)

# Create a DataFrame from the list of stock information
ticker_df = pd.DataFrame(ticker_data, columns=columns)
ticker_df = ticker_df.dropna(how='all', subset=columns[1:])


# Data quality checks
def data_quality_checks(df):
    if df.isnull().values.any():
        raise ValueError("Data contains empty values")

    expected_types = {col: str for col in columns}
    for column, expected_type in expected_types.items():
        if not df[column].map(type).eq(expected_type).all():
            raise TypeError(f"Data type mismatch in column {column}")

    if not df['currency'].str.len().eq(3).all():
        raise ValueError("Currency column contains values not of length 3")

# Perform data quality checks above
data_quality_checks(ticker_df)

# Database connection and insertion
try:
    mydb = mysql.connector.connect(
        host="alvcantu.mysql.pythonanywhere-services.com",
        user="alvcantu",
        password="h63Efp09-d",
        database="alvcantu$default"
    )

    if mydb.is_connected():
        cursor = mydb.cursor()

        # Prepare the INSERT statement into MySQL ST_DimCompany table
        insert_query = """
            INSERT INTO ST_DimCompany (ticker, name, country, website, industry, currency, summary)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            ON DUPLICATE KEY UPDATE
            name=VALUES(name), country=VALUES(country), website=VALUES(website),
            industry=VALUES(industry), currency=VALUES(currency), summary=VALUES(summary)
        """

        # Insert or update rows by executing query above
        cursor.executemany(insert_query, ticker_df.values.tolist())
        mydb.commit()

        print(f"{cursor.rowcount} record(s) upserted.")

# Error clause
except Error as e:
    print(f"Error: {e}")

# Close database
finally:
    if 'mydb' in locals() and mydb.is_connected():
        cursor.close()
        mydb.close()
        print("MySQL connection is closed")